// Copyright (c) 2024 Appliberated (https://www.appliberated.com/). All rights reserved.
// Use of this source code is governed by a user license that can be found in the LICENSE file.
//
// Flutter icons CustomIcons
// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.

/// The custom icons used in the app.
library;

import 'package:flutter/widgets.dart';

const _kFontFam = 'CustomIcons';
const String? _kFontPkg = null;

/// The East-Tec logo mark.
const IconData eastTecLogoMark = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
